### PR TITLE
feat: trimEnd on render

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by cdepillabout** [comment]
@srghma Sorry, I guess I completely missed this PR.

I don't really maintain `purescript-boxes` anymore, but I've passed maintainership over to @pbrant.

@srghma If @pbrant doesn't respond here in a week or so, please feel free to ping me and I'll either merge this in or make you a maintainer so you can merge it in and make a new release.

**Comment by srghma** [comment]
@cdepillabout 

> make you a maintainer

I'm not against this in either case)

**Comment by pbrant** [comment]
Hi Serhii, sorry for overlooking this too. To be honest, I'm a little
skeptical about this change. It seems like it might be surprising behavior
if extra whitespace is removed. It also diverges from the original Haskell
implementation.

**Comment by pbrant** [comment]
@srghma Thanks for the expanded explanation on the haskell-boxes issue. I was thinking additional internal vertical whitespace would potentially be an issue, but that would be somewhat of an abuse of the basic approach boxes takes anyway.

**Comment by srghma** [comment]
@pbrant you are awesome!)

**Pull request merged**
