### PR TITLE
update

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
@pbrant @cdepillabout I would like to be a maintainer

**Comment by srghma** [comment]
the package is not in the https://github.com/purescript/package-sets/blob/master/src/groups/cdepillabout.dhall

**Comment by srghma** [comment]
I would like to make a new release and publish to package-sets

**Comment by srghma** [comment]
tests pass

**Comment by pbrant** [comment]
> @pbrant @cdepillabout I would like to be a maintainer

Sounds good to me.

**Comment by cdepillabout** [comment]
@srghma Great, sent you an invite.

**Comment by srghma** [comment]
awesome, will publish new v

**Pull request merged**
